services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.15
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_4LW_COMMANDS_WHITELIST: "ruok,stat,mntr,conf"
      KAFKA_OPTS: "-Dzookeeper.4lw.commands.whitelist=ruok,stat,mntr,conf"
    healthcheck:
      test: ["CMD", "bash", "-c", "echo ruok | nc localhost 2181 | grep imok"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - app_network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9093,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server kafka:9093 --list || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - app_network

  postgres:
    image: postgres:16-alpine
    hostname: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-portfolio_db}
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  migration-runner:
    build:
      context: .
      dockerfile: ./services/persistence-service/Dockerfile
    hostname: migration-runner
    container_name: migration-runner
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/portfolio_db
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: ["/opt/venv/bin/alembic"]
    command: ["upgrade", "head"]
    networks:
      - app_network

  ingestion-service:
    build:
      context: .
      dockerfile: ./services/ingestion-service/Dockerfile
    hostname: ingestion-service
    container_name: ingestion-service
    ports:
      - "8000:8000"
    environment:
      PYTHONPATH: "/app:/app/libs/portfolio-common"
      KAFKA_BOOTSTRAP_SERVERS: kafka:9093
      KAFKA_RAW_TRANSACTIONS_TOPIC: raw_transactions
      KAFKA_MARKET_PRICES_TOPIC: market_prices
      KAFKA_FX_RATES_TOPIC: fx_rates
      KAFKA_INSTRUMENTS_TOPIC: instruments
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - ./services/ingestion-service/app:/app/app
      - ./libs/portfolio-common:/app/libs/portfolio-common
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4 --timeout-keep-alive 30
    networks:
      - app_network
  
  query-service:
    build:
      context: .
      dockerfile: ./services/query-service/Dockerfile
    hostname: query-service
    container_name: query-service
    ports:
      - "8001:8001"
    environment:
      PYTHONPATH: "/app"
      DATABASE_URL: postgresql://user:password@postgres:5432/portfolio_db
      HOST_DATABASE_URL: ""
    depends_on:
      migration-runner:
        condition: service_completed_successfully
    volumes:
      - ./services/query-service/app:/app/app
      - ./libs/portfolio-common:/app/libs/portfolio-common
    networks:
      - app_network

  persistence-service:
    build:
      context: .
      dockerfile: ./services/persistence-service/Dockerfile
    hostname: persistence-service
    container_name: persistence-service
    environment:
      PYTHONPATH: "/app"
      KAFKA_BOOTSTRAP_SERVERS: kafka:9093
      DATABASE_URL: postgresql://user:password@postgres:5432/portfolio_db
      HOST_DATABASE_URL: ""
    depends_on:
      kafka:
        condition: service_healthy
      migration-runner:
        condition: service_completed_successfully
    volumes:
      - ./services/persistence-service/app:/app/app
      - ./libs/portfolio-common:/app/libs/portfolio-common
    command: ["python", "-m", "app.main"]
    networks:
      - app_network

  cost-calculator-service:
    build:
      context: .
      dockerfile: ./services/calculators/cost-calculator-service/Dockerfile
    hostname: cost-calculator-service
    container_name: cost-calculator-service
    environment:
      PYTHONPATH: "/app:/app/libs/portfolio-common:/app/libs/financial-calculator-engine"
      KAFKA_BOOTSTRAP_SERVERS: kafka:9093
      KAFKA_RAW_TRANSACTIONS_COMPLETED_TOPIC: raw_transactions_completed
      DATABASE_URL: postgresql://user:password@postgres:5432/portfolio_db
    depends_on:
      kafka:
        condition: service_healthy
      migration-runner:
        condition: service_completed_successfully
    volumes:
      - ./services/calculators/cost-calculator-service/app:/app/app
      - ./libs/portfolio-common:/app/libs/portfolio-common
      - ./libs/financial-calculator-engine:/app/libs/financial-calculator-engine
    command: ["python", "app/main.py"]
    networks:
      - app_network

  cashflow-calculator-service:
    build:
      context: .
      dockerfile: ./services/calculators/cashflow-calculator-service/Dockerfile
    hostname: cashflow-calculator-service
    container_name: cashflow-calculator-service
    environment:
      PYTHONPATH: "/app:/app/libs/portfolio-common"
      KAFKA_BOOTSTRAP_SERVERS: kafka:9093
      DATABASE_URL: postgresql://user:password@postgres:5432/portfolio_db
    depends_on:
      kafka:
        condition: service_healthy
      migration-runner:
        condition: service_completed_successfully
    volumes:
      - ./services/calculators/cashflow-calculator-service/app:/app/app
      - ./libs/portfolio-common:/app/libs/portfolio-common
    command: ["python", "-m", "app.main"]
    networks:
      - app_network

  position-calculator-service:
    build:
      context: .
      dockerfile: ./services/calculators/position-calculator/Dockerfile
    hostname: position-calculator-service
    container_name: position-calculator-service
    environment:
      PYTHONPATH: "/app"
      KAFKA_BOOTSTRAP_SERVERS: kafka:9093
      DATABASE_URL: postgresql://user:password@postgres:5432/portfolio_db
      HOST_DATABASE_URL: ""
    depends_on:
      kafka:
        condition: service_healthy
      migration-runner:
        condition: service_completed_successfully
    volumes:
      - ./services/calculators/position-calculator/app:/app/app
      - ./libs/portfolio-common:/app/libs/portfolio-common
    command: ["python", "-m", "app.main"]
    networks:
      - app_network

  position-valuation-calculator:
    build:
      context: .
      dockerfile: ./services/calculators/position-valuation-calculator/Dockerfile
    hostname: position-valuation-calculator
    container_name: position-valuation-calculator
    environment:
      PYTHONPATH: "/app"
      KAFKA_BOOTSTRAP_SERVERS: kafka:9093
      DATABASE_URL: postgresql://user:password@postgres:5432/portfolio_db
      HOST_DATABASE_URL: ""
    depends_on:
      kafka:
        condition: service_healthy
      migration-runner:
        condition: service_completed_successfully
    volumes:
      - ./services/calculators/position-valuation-calculator/app:/app/app
      - ./libs/portfolio-common:/app/libs/portfolio-common
    command: ["python", "-m", "app.main"]
    networks:
      - app_network
  
  timeseries-generator-service:
    build:
      context: .
      dockerfile: ./services/timeseries-generator-service/Dockerfile
    hostname: timeseries-generator-service
    container_name: timeseries-generator-service
    environment:
      PYTHONPATH: "/app:/app/libs/portfolio-common"
      KAFKA_BOOTSTRAP_SERVERS: kafka:9093
      DATABASE_URL: postgresql://user:password@postgres:5432/portfolio_db
    depends_on:
      kafka:
        condition: service_healthy
      migration-runner:
        condition: service_completed_successfully
    volumes:
      - ./services/timeseries-generator-service/app:/app/app
      - ./libs/portfolio-common:/app/libs/portfolio-common
    command: ["python", "-m", "app.main"]
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge