# pyproject.toml
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "portfolio-analytics-system"
version = "0.1.0"
description = "Event-driven system for portfolio analytics."
readme = "README.md"
requires-python = ">=3.11"

[tool.setuptools.packages.find]
where = ["."]
exclude = ["tests*", "deployment*"]

# --- UPDATED: Pytest Configuration for PYTHONPATH and addopts ---
[tool.pytest.ini_options]
# Explicitly tell pytest where to find tests
testpaths = [
    "tests",
    "libs",
    "services"
]
# This explicit path configuration ensures all modules are discoverable
pythonpath = [
    ".",
    "libs/portfolio-common",
    "libs/financial-calculator-engine/src",
    "services/ingestion-service/app",
    "services/persistence_service/app",
    "services/query-service/app",
    "services/calculators/cashflow_calculator_service/app",
    "services/calculators/cost_calculator_service/app",
    "services/calculators/position_calculator/app",
    "services/calculators/position-valuation-calculator/app",
    "services/timeseries-generator-service/app",
    "tools"
]
addopts = "--strict-markers"
minversion = "6.0"
# Add registration for the asyncio marker
markers = [
    "asyncio: mark a test as being an asyncio test",
]
filterwarnings = [
    "ignore:Please use `import python_multipart` instead.:PendingDeprecationWarning"
]