# pyproject.toml
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "portfolio-analytics-system"
version = "0.1.0"
description = "Event-driven system for portfolio analytics."
readme = "README.md"
requires-python = ">=3.11"

[tool.setuptools.packages.find]
where = ["."]
exclude = ["tests*", "deployment*"]

[tool.pytest.ini_options]
# The test root is now the single top-level tests directory
testpaths = [
    "tests"
]
pythonpath = [
    ".",
    "libs/portfolio-common",
    "libs/financial-calculator-engine/src",
    "services/ingestion_service",
    "services/persistence_service",
    "services/query_service",
    "services/calculators/cashflow_calculator_service",
    "services/calculators/cost_calculator_service",
    "services/calculators/position_calculator",
    "services/calculators/position_valuation_calculator",
    "services/timeseries_generator_service",
]
addopts = "--strict-markers"
minversion = "6.0"
markers = [
    "asyncio: mark a test as being an asyncio test",
]
filterwarnings = [
    "ignore:Please use `import python_multipart` instead.:PendingDeprecationWarning"
]