# prometheus/prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ingestion_service'
    static_configs:
      - targets: ['ingestion_service:8000']
  - job_name: 'query_service'
    static_configs:
      - targets: ['query_service:8001']
  - job_name: 'persistence_service'
    static_configs:
      - targets: ['persistence_service:8080']
  - job_name: 'position_calculator_service'
    static_configs:
      - targets: ['position_calculator_service:8081']
  - job_name: 'cashflow_calculator_service'
    static_configs:
      - targets: ['cashflow_calculator_service:8082']
  - job_name: 'cost_calculator_service'
    static_configs:
      - targets: ['cost_calculator_service:8083']
  - job_name: 'position_valuation_calculator'
    static_configs:
      - targets: ['position_valuation_calculator:8084']
  - job_name: 'timeseries_generator_service'
    static_configs:
      - targets: ['timeseries_generator_service:8085']