"""feat: Add explicit portfolio and position cashflows to timeseries

Revision ID: 5a7b3c2d1e0f
Revises: 2b1a3c4d5e6f
Create Date: 2025-08-20 08:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a7b3c2d1e0f'
down_revision: Union[str, None] = '2b1a3c4d5e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('position_timeseries', sa.Column('bod_cashflow_position', sa.Numeric(precision=18, scale=10), nullable=False, server_default=sa.text("'0'::numeric")))
    op.add_column('position_timeseries', sa.Column('eod_cashflow_position', sa.Numeric(precision=18, scale=10), nullable=False, server_default=sa.text("'0'::numeric")))
    op.add_column('position_timeseries', sa.Column('bod_cashflow_portfolio', sa.Numeric(precision=18, scale=10), nullable=False, server_default=sa.text("'0'::numeric")))
    op.add_column('position_timeseries', sa.Column('eod_cashflow_portfolio', sa.Numeric(precision=18, scale=10), nullable=False, server_default=sa.text("'0'::numeric")))
    op.alter_column('position_timeseries', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               server_default=sa.text('now()'))
    op.alter_column('position_timeseries', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               server_default=sa.text('now()'))
    op.drop_column('position_timeseries', 'eod_cashflow')
    op.drop_column('position_timeseries', 'bod_cashflow')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('position_timeseries', sa.Column('bod_cashflow', sa.NUMERIC(precision=18, scale=10), autoincrement=False, nullable=False))
    op.add_column('position_timeseries', sa.Column('eod_cashflow', sa.NUMERIC(precision=18, scale=10), autoincrement=False, nullable=False))
    op.alter_column('position_timeseries', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               server_default=None)
    op.alter_column('position_timeseries', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               server_default=None)
    op.drop_column('position_timeseries', 'eod_cashflow_portfolio')
    op.drop_column('position_timeseries', 'bod_cashflow_portfolio')
    op.drop_column('position_timeseries', 'eod_cashflow_position')
    op.drop_column('position_timeseries', 'bod_cashflow_position')
    # ### end Alembic commands ###