"""feat: Add daily_performance_metrics table

Revision ID: 13f0d8f9e1df
Revises: e91fbfa909c4
Create Date: 2025-08-17 12:16:51.559653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13f0d8f9e1df'
down_revision: Union[str, None] = 'e91fbfa909c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_performance_metrics',
    sa.Column('portfolio_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('return_basis', sa.String(), nullable=False),
    sa.Column('linking_factor', sa.Numeric(precision=28, scale=18), nullable=False),
    sa.Column('daily_return_pct', sa.Numeric(precision=28, scale=18), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.portfolio_id'], ),
    sa.PrimaryKeyConstraint('portfolio_id', 'date', 'return_basis')
    )
    op.create_index(op.f('ix_daily_performance_metrics_date'), 'daily_performance_metrics', ['date'], unique=False)
    op.create_index('ix_daily_performance_metrics_portfolio_date_basis', 'daily_performance_metrics', ['portfolio_id', 'date', 'return_basis'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_daily_performance_metrics_portfolio_date_basis', table_name='daily_performance_metrics')
    op.drop_index(op.f('ix_daily_performance_metrics_date'), table_name='daily_performance_metrics')
    op.drop_table('daily_performance_metrics')
    # ### end Alembic commands ###
