"""feat: add time series tables

Revision ID: 1403410a2157
Revises: 8ff3cc405907
Create Date: 2025-07-29 22:46:06.872709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1403410a2157'
down_revision: Union[str, None] = '8ff3cc405907'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_timeseries',
    sa.Column('portfolio_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('bod_market_value', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('bod_cashflow', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('eod_cashflow', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('eod_market_value', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('fees', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.portfolio_id'], ),
    sa.PrimaryKeyConstraint('portfolio_id', 'date')
    )
    op.create_table('position_timeseries',
    sa.Column('portfolio_id', sa.String(), nullable=False),
    sa.Column('security_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('bod_market_value', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('bod_cashflow', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('eod_cashflow', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('eod_market_value', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('fees', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('cost', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.portfolio_id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['instruments.security_id'], ),
    sa.PrimaryKeyConstraint('portfolio_id', 'security_id', 'date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('position_timeseries')
    op.drop_table('portfolio_timeseries')
    # ### end Alembic commands ###
