"""feat: Add cashflow_rules table

Revision ID: 1a7b8c9d0e2f
Revises: 3a9c7b2d1e0f
Create Date: 2025-09-02 08:04:23.184329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a7b8c9d0e2f'
down_revision: Union[str, None] = '3a9c7b2d1e0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    cashflow_rules_table = op.create_table('cashflow_rules',
        sa.Column('transaction_type', sa.String(length=50), nullable=False),
        sa.Column('classification', sa.String(length=50), nullable=False),
        sa.Column('timing', sa.String(length=10), nullable=False),
        sa.Column('is_position_flow', sa.Boolean(), nullable=False),
        sa.Column('is_portfolio_flow', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('transaction_type')
    )
    # ### end Alembic commands ###

    # --- Data Migration: Move hardcoded rules from the old config into the new table ---
    op.bulk_insert(
        cashflow_rules_table,
        [
            {'transaction_type': 'BUY', 'classification': 'INVESTMENT_OUTFLOW', 'timing': 'BOD', 'is_position_flow': True, 'is_portfolio_flow': False},
            {'transaction_type': 'SELL', 'classification': 'INVESTMENT_INFLOW', 'timing': 'EOD', 'is_position_flow': True, 'is_portfolio_flow': False},
            {'transaction_type': 'DIVIDEND', 'classification': 'INCOME', 'timing': 'EOD', 'is_position_flow': True, 'is_portfolio_flow': False},
            {'transaction_type': 'INTEREST', 'classification': 'INCOME', 'timing': 'EOD', 'is_position_flow': True, 'is_portfolio_flow': False},
            {'transaction_type': 'FEE', 'classification': 'EXPENSE', 'timing': 'EOD', 'is_position_flow': True, 'is_portfolio_flow': True},
            {'transaction_type': 'TAX', 'classification': 'EXPENSE', 'timing': 'EOD', 'is_position_flow': True, 'is_portfolio_flow': False},
            {'transaction_type': 'TRANSFER_IN', 'classification': 'TRANSFER', 'timing': 'BOD', 'is_position_flow': True, 'is_portfolio_flow': True},
            {'transaction_type': 'DEPOSIT', 'classification': 'CASHFLOW_IN', 'timing': 'BOD', 'is_position_flow': True, 'is_portfolio_flow': True},
            {'transaction_type': 'TRANSFER_OUT', 'classification': 'TRANSFER', 'timing': 'EOD', 'is_position_flow': True, 'is_portfolio_flow': True},
            {'transaction_type': 'WITHDRAWAL', 'classification': 'CASHFLOW_OUT', 'timing': 'EOD', 'is_position_flow': True, 'is_portfolio_flow': True},
        ]
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cashflow_rules')
    # ### end Alembic commands ###