"""feat: add valuation_status to daily_position_snapshots

Revision ID: 2431c840d504
Revises: 84dd2172ef66
Create Date: 2025-08-07 16:09:59.235182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2431c840d504'
down_revision: Union[str, None] = '84dd2172ef66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
