"""feat: Add reprocessing_jobs table

Revision ID: 2e3ca6475106
Revises: 4c556af050aa
Create Date: 2025-09-01 22:14:58.926429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e3ca6475106'
down_revision: Union[str, None] = '4c556af050aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reprocessing_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reprocessing_jobs_job_type'), 'reprocessing_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_reprocessing_jobs_status'), 'reprocessing_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reprocessing_jobs_status'), table_name='reprocessing_jobs')
    op.drop_index(op.f('ix_reprocessing_jobs_job_type'), table_name='reprocessing_jobs')
    op.drop_table('reprocessing_jobs')
    # ### end Alembic commands ###
