"""feat: add columns for dual-currency cost tracking

Revision ID: 300bf2c4aad6
Revises: 45c3cea614f5
Create Date: 2025-08-08 23:03:34.518572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '300bf2c4aad6'
down_revision: Union[str, None] = '45c3cea614f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_position_snapshots', sa.Column('cost_basis_local', sa.Numeric(precision=18, scale=10), nullable=True))
    op.add_column('daily_position_snapshots', sa.Column('market_value_local', sa.Numeric(precision=18, scale=10), nullable=True))
    op.add_column('daily_position_snapshots', sa.Column('unrealized_gain_loss_local', sa.Numeric(precision=18, scale=10), nullable=True))
    op.add_column('position_history', sa.Column('cost_basis_local', sa.Numeric(precision=18, scale=10), nullable=True))
    op.add_column('transactions', sa.Column('transaction_fx_rate', sa.Numeric(precision=18, scale=10), nullable=True))
    op.add_column('transactions', sa.Column('net_cost_local', sa.Numeric(precision=18, scale=10), nullable=True))
    op.add_column('transactions', sa.Column('realized_gain_loss_local', sa.Numeric(precision=18, scale=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'realized_gain_loss_local')
    op.drop_column('transactions', 'net_cost_local')
    op.drop_column('transactions', 'transaction_fx_rate')
    op.drop_column('position_history', 'cost_basis_local')
    op.drop_column('daily_position_snapshots', 'unrealized_gain_loss_local')
    op.drop_column('daily_position_snapshots', 'market_value_local')
    op.drop_column('daily_position_snapshots', 'cost_basis_local')
    # ### end Alembic commands ###
