"""add composite index on transactions portfolio and security

Revision ID: 37cd0a61d223
Revises: ae1f67a6912f
Create Date: 2025-08-05 14:46:49.838129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37cd0a61d223'
down_revision: Union[str, None] = 'ae1f67a6912f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_transactions_portfolio_security', 'transactions', ['portfolio_id', 'security_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_portfolio_security', table_name='transactions')
    # ### end Alembic commands ###
