"""feat: Add cost_basis_method to portfolios table

Revision ID: 3a9c7b2d1e0f
Revises: 2e3ca6475106
Create Date: 2025-09-02 06:50:10.123456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a9c7b2d1e0f'
down_revision: Union[str, None] = '2e3ca6475106'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('cost_basis_method', sa.String(), server_default='FIFO', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'cost_basis_method')
    # ### end Alembic commands ###