"""fix: remove unique constraint from position_history transaction_id

Revision ID: 3e9e08c2a2b5
Revises: 1403410a2157
Create Date: 2025-07-29 23:46:57.364186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e9e08c2a2b5'
down_revision: Union[str, None] = '1403410a2157'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('position_history_transaction_id_key', 'position_history', type_='unique')
    op.create_unique_constraint('_portfolio_security_date_txn_uc', 'position_history', ['portfolio_id', 'security_id', 'position_date', 'transaction_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_portfolio_security_date_txn_uc', 'position_history', type_='unique')
    op.create_unique_constraint('position_history_transaction_id_key', 'position_history', ['transaction_id'])
    # ### end Alembic commands ###
