"""feat: Remove unique constraint from recalculation_jobs

Revision ID: 41f42bda6d1e
Revises: bfe95fef89d8
Create Date: 2025-08-24 11:55:10.223247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41f42bda6d1e'
down_revision: Union[str, None] = 'bfe95fef89d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_portfolio_security_recalc_uc', 'recalculation_jobs', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_portfolio_security_recalc_uc', 'recalculation_jobs', ['portfolio_id', 'security_id'])
    # ### end Alembic commands ###