"""feat: Add issuer fields to instruments table

Revision ID: 431d0c452afa
Revises: 6acc877cf070
Create Date: 2025-08-31 16:01:01.562114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '431d0c452afa'
down_revision: Union[str, None] = '6acc877cf070'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruments', sa.Column('issuer_id', sa.String(), nullable=True))
    op.add_column('instruments', sa.Column('ultimate_parent_issuer_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_instruments_issuer_id'), 'instruments', ['issuer_id'], unique=False)
    op.create_index(op.f('ix_instruments_ultimate_parent_issuer_id'), 'instruments', ['ultimate_parent_issuer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instruments_ultimate_parent_issuer_id'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_issuer_id'), table_name='instruments')
    op.drop_column('instruments', 'ultimate_parent_issuer_id')
    op.drop_column('instruments', 'issuer_id')
    # ### end Alembic commands ###
