"""feat: add portfolio_aggregation_jobs table

Revision ID: 45c3cea614f5
Revises: 2431c840d504
Create Date: 2025-08-07 17:41:34.991907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45c3cea614f5'
down_revision: Union[str, None] = '2431c840d504'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_aggregation_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.String(), nullable=False),
    sa.Column('aggregation_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'aggregation_date', name='_portfolio_date_uc')
    )
    op.create_index(op.f('ix_portfolio_aggregation_jobs_aggregation_date'), 'portfolio_aggregation_jobs', ['aggregation_date'], unique=False)
    op.create_index(op.f('ix_portfolio_aggregation_jobs_portfolio_id'), 'portfolio_aggregation_jobs', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_portfolio_aggregation_jobs_status'), 'portfolio_aggregation_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_aggregation_jobs_status'), table_name='portfolio_aggregation_jobs')
    op.drop_index(op.f('ix_portfolio_aggregation_jobs_portfolio_id'), table_name='portfolio_aggregation_jobs')
    op.drop_index(op.f('ix_portfolio_aggregation_jobs_aggregation_date'), table_name='portfolio_aggregation_jobs')
    op.drop_table('portfolio_aggregation_jobs')
    # ### end Alembic commands ###
