"""feat: Add server-side timestamp defaults and NOT NULL constraints

Revision ID: <YOUR_NEW_REVISION_ID>
Revises: 75296ff1ae2b
Create Date: 2025-08-22 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '<YOUR_NEW_REVISION_ID>'
down_revision: Union[str, None] = '75296ff1ae2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('business_dates', 'created_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=False,
               server_default=sa.text('now()'))
    op.alter_column('cashflows', 'created_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=False,
               server_default=sa.text('now()'))
    op.alter_column('cashflows', 'updated_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=False,
               server_default=sa.text('now()'))
    op.alter_column('daily_position_snapshots', 'created_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=False,
               server_default=sa.text('now()'))
    op.alter_column('daily_position_snapshots', 'updated_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=False,
               server_default=sa.text('now()'))
    op.alter_column('fx_rates', 'created_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=False,
               server_default=sa.text('now()'))
    op.alter_column('fx_rates', 'updated_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=False,
               server_default=sa.text('now()'))
    op.alter_column('instruments', 'created_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=False,
               server_default=sa.text('now()'))
    op.alter_column('instruments', 'updated_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=False,
               server_default=sa.text('now()'))
    op.alter_column('market_prices', 'created_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=False,
               server_default=sa.text('now()'))
    op.alter_column('market_prices', 'updated_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=False,
               server_default=sa.text('now()'))
    op.alter_column('outbox_events', 'created_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=False,
               server_default=sa.text('now()'))
    op.alter_column('portfolio_aggregation_jobs', 'created_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=False,
               server_default=sa.text('now()'))
    op.alter_column('portfolio_aggregation_jobs', 'updated_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=False,
               server_default=sa.text('now()'))
    op.alter_column('portfolio_valuation_jobs', 'created_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=False,
               server_default=sa.text('now()'))
    op.alter_column('portfolio_valuation_jobs', 'updated_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=False,
               server_default=sa.text('now()'))
    op.alter_column('portfolios', 'created_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=False,
               server_default=sa.text('now()'))
    op.alter_column('portfolios', 'updated_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=False,
               server_default=sa.text('now()'))
    op.alter_column('position_history', 'created_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=False,
               server_default=sa.text('now()'))
    op.alter_column('position_history', 'updated_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=False,
               server_default=sa.text('now()'))
    op.alter_column('position_timeseries', 'created_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=False,
               server_default=sa.text('now()'))
    op.alter_column('position_timeseries', 'updated_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=False,
               server_default=sa.text('now()'))
    op.alter_column('portfolio_timeseries', 'created_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=False,
               server_default=sa.text('now()'))
    op.alter_column('portfolio_timeseries', 'updated_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=False,
               server_default=sa.text('now()'))
    op.alter_column('transaction_costs', 'created_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=False,
               server_default=sa.text('now()'))
    op.alter_column('transaction_costs', 'updated_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=False,
               server_default=sa.text('now()'))
    op.alter_column('transactions', 'created_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=False,
               server_default=sa.text('now()'))
    op.alter_column('transactions', 'updated_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=False,
               server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'updated_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=True,
               server_default=None)
    op.alter_column('transactions', 'created_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=True,
               server_default=None)
    op.alter_column('transaction_costs', 'updated_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=True,
               server_default=None)
    op.alter_column('transaction_costs', 'created_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=True,
               server_default=None)
    op.alter_column('portfolio_timeseries', 'updated_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=True,
               server_default=None)
    op.alter_column('portfolio_timeseries', 'created_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=True,
               server_default=None)
    op.alter_column('position_timeseries', 'updated_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=True,
               server_default=None)
    op.alter_column('position_timeseries', 'created_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=True,
               server_default=None)
    op.alter_column('position_history', 'updated_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=True,
               server_default=None)
    op.alter_column('position_history', 'created_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=True,
               server_default=None)
    op.alter_column('portfolios', 'updated_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=True,
               server_default=None)
    op.alter_column('portfolios', 'created_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=True,
               server_default=None)
    op.alter_column('portfolio_valuation_jobs', 'updated_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=True,
               server_default=None)
    op.alter_column('portfolio_valuation_jobs', 'created_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=True,
               server_default=None)
    op.alter_column('portfolio_aggregation_jobs', 'updated_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=True,
               server_default=None)
    op.alter_column('portfolio_aggregation_jobs', 'created_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=True,
               server_default=None)
    op.alter_column('outbox_events', 'created_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=False,
               server_default=None)
    op.alter_column('market_prices', 'updated_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=True,
               server_default=None)
    op.alter_column('market_prices', 'created_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=True,
               server_default=None)
    op.alter_column('instruments', 'updated_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=True,
               server_default=None)
    op.alter_column('instruments', 'created_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=True,
               server_default=None)
    op.alter_column('fx_rates', 'updated_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=True,
               server_default=None)
    op.alter_column('fx_rates', 'created_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=True,
               server_default=None)
    op.alter_column('daily_position_snapshots', 'updated_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=True,
               server_default=None)
    op.alter_column('daily_position_snapshots', 'created_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=True,
               server_default=None)
    op.alter_column('cashflows', 'updated_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=True,
               server_default=None)
    op.alter_column('cashflows', 'created_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=True,
               server_default=None)
    op.alter_column('business_dates', 'created_at',
               existing_type=sa.DATETIME(timezone=True),
               nullable=True,
               server_default=None)
    # ### end Alembic commands ###