"""feat(db): Add instrument_reprocessing_state table

Revision ID: 4c556af050aa
Revises: 431d0c452afa
Create Date: 2025-08-31 21:08:50.097110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c556af050aa'
down_revision: Union[str, None] = '431d0c452afa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instrument_reprocessing_state',
    sa.Column('security_id', sa.String(), nullable=False),
    sa.Column('earliest_impacted_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('security_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instrument_reprocessing_state')
    # ### end Alembic commands ###
