"""feat: Add epoch column to cashflows table

Revision ID: 50f1222afe00
Revises: b25f9ec89ae3
Create Date: 2025-08-28 21:15:38.683240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50f1222afe00'
down_revision: Union[str, None] = 'b25f9ec89ae3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cashflows', sa.Column('epoch', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cashflows', 'epoch')
    # ### end Alembic commands ###