"""feat: add cashflows table

Revision ID: 5acfa4e4da10
Revises: 90d075cd069e
Create Date: 2025-07-28 20:28:18.125246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5acfa4e4da10'
down_revision: Union[str, None] = '90d075cd069e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cashflows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('portfolio_id', sa.String(), nullable=False),
    sa.Column('security_id', sa.String(), nullable=True),
    sa.Column('cashflow_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('classification', sa.String(), nullable=False),
    sa.Column('timing', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('calculation_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id', name='_transaction_id_uc')
    )
    op.create_index(op.f('ix_cashflows_cashflow_date'), 'cashflows', ['cashflow_date'], unique=False)
    op.create_index(op.f('ix_cashflows_portfolio_id'), 'cashflows', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_cashflows_security_id'), 'cashflows', ['security_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cashflows_security_id'), table_name='cashflows')
    op.drop_index(op.f('ix_cashflows_portfolio_id'), table_name='cashflows')
    op.drop_index(op.f('ix_cashflows_cashflow_date'), table_name='cashflows')
    op.drop_table('cashflows')
    # ### end Alembic commands ###
