"""refactor: redesign position_history table for snapshots

Revision ID: 61aba93ba496
Revises: ce5e5ea23c0f
Create Date: 2025-07-30 00:20:42.649297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61aba93ba496'
down_revision: Union[str, None] = 'ce5e5ea23c0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('position_history', sa.Column('snapshot_type', sa.String(), nullable=False))
    op.alter_column('position_history', 'transaction_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('position_history', 'transaction_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('position_history', 'snapshot_type')
    # ### end Alembic commands ###
