"""feat: Add correlation and retry columns to outbox_events

Revision ID: 675879892070
Revises: 06d19bb5cf88
Create Date: 2025-08-02 18:01:26.230999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '675879892070'
down_revision: Union[str, None] = '06d19bb5cf88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox_events', sa.Column('correlation_id', sa.String(), nullable=True))
    op.add_column('outbox_events', sa.Column('retry_count', sa.Integer(), nullable=False))
    op.add_column('outbox_events', sa.Column('last_attempted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outbox_events', 'last_attempted_at')
    op.drop_column('outbox_events', 'retry_count')
    op.drop_column('outbox_events', 'correlation_id')
    # ### end Alembic commands ###
