"""feat: Add asset allocation fields to instruments table

Revision ID: 6acc877cf070
Revises: 50f1222afe00
Create Date: 2025-08-30 09:16:23.077286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6acc877cf070'
down_revision: Union[str, None] = '50f1222afe00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruments', sa.Column('asset_class', sa.String(), nullable=True))
    op.add_column('instruments', sa.Column('sector', sa.String(), nullable=True))
    op.add_column('instruments', sa.Column('country_of_risk', sa.String(), nullable=True))
    op.add_column('instruments', sa.Column('rating', sa.String(), nullable=True))
    op.add_column('instruments', sa.Column('maturity_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instruments', 'maturity_date')
    op.drop_column('instruments', 'rating')
    op.drop_column('instruments', 'country_of_risk')
    op.drop_column('instruments', 'sector')
    op.drop_column('instruments', 'asset_class')
    # ### end Alembic commands ###