"""feat: Add correlation_id to processed_events table

Revision ID: 75cfaf91df57
Revises: 24f7983e5acd
Create Date: 2025-08-01 13:55:09.553637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'c824b2f1a6e9'
down_revision: Union[str, None] = '24f7983e5acd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processed_events', sa.Column('correlation_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processed_events', 'correlation_id')
    # ### end Alembic commands ###
