"""feat: Add recalculation_jobs table

Revision ID: 88a8f0488b1c
Revises: 4b0c9313f9b9
Create Date: 2025-08-22 17:16:10.014354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88a8f0488b1c'
down_revision: Union[str, None] = '4b0c9313f9b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recalculation_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.String(), nullable=False),
    sa.Column('security_id', sa.String(), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'security_id', name='_portfolio_security_recalc_uc')
    )
    op.create_index(op.f('ix_recalculation_jobs_portfolio_id'), 'recalculation_jobs', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_recalculation_jobs_security_id'), 'recalculation_jobs', ['security_id'], unique=False)
    op.create_index(op.f('ix_recalculation_jobs_status'), 'recalculation_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recalculation_jobs_status'), table_name='recalculation_jobs')
    op.drop_index(op.f('ix_recalculation_jobs_security_id'), table_name='recalculation_jobs')
    op.drop_index(op.f('ix_recalculation_jobs_portfolio_id'), table_name='recalculation_jobs')
    op.drop_table('recalculation_jobs')
    # ### end Alembic commands ###