"""feat: add portfolios table

Revision ID: 8ff3cc405907
Revises: fac2be404322
Create Date: 2025-07-29 21:36:33.280735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ff3cc405907'
down_revision: Union[str, None] = 'fac2be404322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.String(), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('open_date', sa.Date(), nullable=False),
    sa.Column('close_date', sa.Date(), nullable=True),
    sa.Column('risk_exposure', sa.String(), nullable=False),
    sa.Column('investment_time_horizon', sa.String(), nullable=False),
    sa.Column('portfolio_type', sa.String(), nullable=False),
    sa.Column('objective', sa.String(), nullable=True),
    sa.Column('booking_center', sa.String(), nullable=False),
    sa.Column('cif_id', sa.String(), nullable=False),
    sa.Column('is_leverage_allowed', sa.Boolean(), nullable=False),
    sa.Column('advisor_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_cif_id'), 'portfolios', ['cif_id'], unique=False)
    op.create_index(op.f('ix_portfolios_portfolio_id'), 'portfolios', ['portfolio_id'], unique=True)
    op.create_foreign_key(None, 'cashflows', 'portfolios', ['portfolio_id'], ['portfolio_id'])
    op.create_foreign_key(None, 'position_history', 'portfolios', ['portfolio_id'], ['portfolio_id'])
    op.create_foreign_key(None, 'transactions', 'portfolios', ['portfolio_id'], ['portfolio_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'position_history', type_='foreignkey')
    op.drop_constraint(None, 'cashflows', type_='foreignkey')
    op.drop_index(op.f('ix_portfolios_portfolio_id'), table_name='portfolios')
    op.drop_index(op.f('ix_portfolios_cif_id'), table_name='portfolios')
    op.drop_table('portfolios')
    # ### end Alembic commands ###
