"""add valuation fields to position_history

Revision ID: 90d075cd069e
Revises: a36bb506a108
Create Date: 2025-07-26 19:29:31.483646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90d075cd069e'
down_revision: Union[str, None] = 'a36bb506a108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('position_history', sa.Column('market_price', sa.Numeric(precision=18, scale=10), nullable=True))
    op.add_column('position_history', sa.Column('market_value', sa.Numeric(precision=18, scale=10), nullable=True))
    op.add_column('position_history', sa.Column('unrealized_gain_loss', sa.Numeric(precision=18, scale=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('position_history', 'unrealized_gain_loss')
    op.drop_column('position_history', 'market_value')
    op.drop_column('position_history', 'market_price')
    # ### end Alembic commands ###
