"""add position_history table

Revision ID: a36bb506a108
Revises: e6e52cac066a
Create Date: 2025-07-25 23:54:48.665026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a36bb506a108'
down_revision: Union[str, None] = 'e6e52cac066a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.String(), nullable=False),
    sa.Column('security_id', sa.String(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('position_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('cost_basis', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_index(op.f('ix_position_history_portfolio_id'), 'position_history', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_position_history_position_date'), 'position_history', ['position_date'], unique=False)
    op.create_index(op.f('ix_position_history_security_id'), 'position_history', ['security_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_position_history_security_id'), table_name='position_history')
    op.drop_index(op.f('ix_position_history_position_date'), table_name='position_history')
    op.drop_index(op.f('ix_position_history_portfolio_id'), table_name='position_history')
    op.drop_table('position_history')
    # ### end Alembic commands ###
