"""feat: Initial schema

Revision ID: ae1f67a6912f
Revises: 
Create Date: 2025-08-04 20:56:42.170034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae1f67a6912f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fx_rates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_currency', sa.String(length=3), nullable=False),
    sa.Column('to_currency', sa.String(length=3), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_currency', 'to_currency', 'rate_date', name='_currency_pair_date_uc')
    )
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('security_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('isin', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('product_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isin')
    )
    op.create_index(op.f('ix_instruments_security_id'), 'instruments', ['security_id'], unique=True)
    op.create_table('market_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('security_id', sa.String(), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('security_id', 'price_date', name='_security_price_date_uc')
    )
    op.create_index(op.f('ix_market_prices_security_id'), 'market_prices', ['security_id'], unique=False)
    op.create_table('outbox_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aggregate_type', sa.String(), nullable=False),
    sa.Column('aggregate_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_attempted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_events_aggregate_id'), 'outbox_events', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_outbox_events_aggregate_type'), 'outbox_events', ['aggregate_type'], unique=False)
    op.create_index(op.f('ix_outbox_events_status'), 'outbox_events', ['status'], unique=False)
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.String(), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('open_date', sa.Date(), nullable=False),
    sa.Column('close_date', sa.Date(), nullable=True),
    sa.Column('risk_exposure', sa.String(), nullable=False),
    sa.Column('investment_time_horizon', sa.String(), nullable=False),
    sa.Column('portfolio_type', sa.String(), nullable=False),
    sa.Column('objective', sa.String(), nullable=True),
    sa.Column('booking_center', sa.String(), nullable=False),
    sa.Column('cif_id', sa.String(), nullable=False),
    sa.Column('is_leverage_allowed', sa.Boolean(), nullable=False),
    sa.Column('advisor_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_cif_id'), 'portfolios', ['cif_id'], unique=False)
    op.create_index(op.f('ix_portfolios_portfolio_id'), 'portfolios', ['portfolio_id'], unique=True)
    op.create_table('processed_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('portfolio_id', sa.String(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'service_name', name='_event_service_uc')
    )
    op.create_table('daily_position_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.String(), nullable=False),
    sa.Column('security_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('cost_basis', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('market_price', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('market_value', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('unrealized_gain_loss', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.portfolio_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'security_id', 'date', name='_portfolio_security_date_uc')
    )
    op.create_index(op.f('ix_daily_position_snapshots_date'), 'daily_position_snapshots', ['date'], unique=False)
    op.create_index(op.f('ix_daily_position_snapshots_portfolio_id'), 'daily_position_snapshots', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_daily_position_snapshots_security_id'), 'daily_position_snapshots', ['security_id'], unique=False)
    op.create_table('portfolio_timeseries',
    sa.Column('portfolio_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('bod_market_value', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('bod_cashflow', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('eod_cashflow', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('eod_market_value', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('fees', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.portfolio_id'], ),
    sa.PrimaryKeyConstraint('portfolio_id', 'date')
    )
    op.create_table('position_timeseries',
    sa.Column('portfolio_id', sa.String(), nullable=False),
    sa.Column('security_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('bod_market_value', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('bod_cashflow', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('eod_cashflow', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('eod_market_value', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('fees', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('cost', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.portfolio_id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['instruments.security_id'], ),
    sa.PrimaryKeyConstraint('portfolio_id', 'security_id', 'date')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('portfolio_id', sa.String(), nullable=False),
    sa.Column('instrument_id', sa.String(), nullable=False),
    sa.Column('security_id', sa.String(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('gross_transaction_amount', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('trade_currency', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('settlement_date', sa.DateTime(), nullable=True),
    sa.Column('trade_fee', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('gross_cost', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('net_cost', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('realized_gain_loss', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.portfolio_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_transaction_id'), 'transactions', ['transaction_id'], unique=True)
    op.create_table('cashflows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('portfolio_id', sa.String(), nullable=False),
    sa.Column('security_id', sa.String(), nullable=True),
    sa.Column('cashflow_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('classification', sa.String(), nullable=False),
    sa.Column('timing', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('calculation_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.portfolio_id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id', name='_transaction_id_uc')
    )
    op.create_index(op.f('ix_cashflows_cashflow_date'), 'cashflows', ['cashflow_date'], unique=False)
    op.create_index(op.f('ix_cashflows_portfolio_id'), 'cashflows', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_cashflows_security_id'), 'cashflows', ['security_id'], unique=False)
    op.create_table('position_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.String(), nullable=False),
    sa.Column('security_id', sa.String(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('position_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('cost_basis', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.portfolio_id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_position_history_portfolio_id'), 'position_history', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_position_history_position_date'), 'position_history', ['position_date'], unique=False)
    op.create_index(op.f('ix_position_history_security_id'), 'position_history', ['security_id'], unique=False)
    op.create_table('transaction_costs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('fee_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_costs')
    op.drop_index(op.f('ix_position_history_security_id'), table_name='position_history')
    op.drop_index(op.f('ix_position_history_position_date'), table_name='position_history')
    op.drop_index(op.f('ix_position_history_portfolio_id'), table_name='position_history')
    op.drop_table('position_history')
    op.drop_index(op.f('ix_cashflows_security_id'), table_name='cashflows')
    op.drop_index(op.f('ix_cashflows_portfolio_id'), table_name='cashflows')
    op.drop_index(op.f('ix_cashflows_cashflow_date'), table_name='cashflows')
    op.drop_table('cashflows')
    op.drop_index(op.f('ix_transactions_transaction_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('position_timeseries')
    op.drop_table('portfolio_timeseries')
    op.drop_index(op.f('ix_daily_position_snapshots_security_id'), table_name='daily_position_snapshots')
    op.drop_index(op.f('ix_daily_position_snapshots_portfolio_id'), table_name='daily_position_snapshots')
    op.drop_index(op.f('ix_daily_position_snapshots_date'), table_name='daily_position_snapshots')
    op.drop_table('daily_position_snapshots')
    op.drop_table('processed_events')
    op.drop_index(op.f('ix_portfolios_portfolio_id'), table_name='portfolios')
    op.drop_index(op.f('ix_portfolios_cif_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_outbox_events_status'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_aggregate_type'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_aggregate_id'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index(op.f('ix_market_prices_security_id'), table_name='market_prices')
    op.drop_table('market_prices')
    op.drop_index(op.f('ix_instruments_security_id'), table_name='instruments')
    op.drop_table('instruments')
    op.drop_table('fx_rates')
    # ### end Alembic commands ###
