"""add market_prices table

Revision ID: b24d937699f5
Revises: 9673c06cf6b6
Create Date: 2025-07-25 21:41:18.727027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b24d937699f5'
down_revision: Union[str, None] = '9673c06cf6b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('security_id', sa.String(), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('security_id', 'price_date', name='_security_price_date_uc')
    )
    op.create_index(op.f('ix_market_prices_security_id'), 'market_prices', ['security_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_prices_security_id'), table_name='market_prices')
    op.drop_table('market_prices')
    # ### end Alembic commands ###
