"""fix: remove unique constraint on transaction_id in position_history

Revision ID: ce5e5ea23c0f
Revises: 3e9e08c2a2b5
Create Date: 2025-07-29 23:58:05.553169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce5e5ea23c0f'
down_revision: Union[str, None] = '3e9e08c2a2b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_portfolio_security_date_txn_uc', 'position_history', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_portfolio_security_date_txn_uc', 'position_history', ['portfolio_id', 'security_id', 'position_date', 'transaction_id'])
    # ### end Alembic commands ###
