"""Add cost columns to transactions table

Revision ID: cea1fe8e6f62
Revises: 6667dbf8a364
Create Date: 2025-07-21 01:58:37.622915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cea1fe8e6f62'
down_revision: Union[str, None] = '6667dbf8a364'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('gross_cost', sa.Numeric(precision=18, scale=10), nullable=True))
    op.add_column('transactions', sa.Column('net_cost', sa.Numeric(precision=18, scale=10), nullable=True))
    op.add_column('transactions', sa.Column('realized_gain_loss', sa.Numeric(precision=18, scale=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'realized_gain_loss')
    op.drop_column('transactions', 'net_cost')
    op.drop_column('transactions', 'gross_cost')
    # ### end Alembic commands ###
