"""Create initial schema

Revision ID: d52f17866f0d
Revises: 
Create Date: 2025-07-21 02:41:20.671729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd52f17866f0d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('portfolio_id', sa.String(), nullable=False),
    sa.Column('instrument_id', sa.String(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('settlement_date', sa.DateTime(), nullable=True),
    sa.Column('trade_fee', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('gross_cost', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('net_cost', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('realized_gain_loss', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_transaction_id'), 'transactions', ['transaction_id'], unique=True)
    op.create_table('transaction_costs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('fee_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_costs')
    op.drop_index(op.f('ix_transactions_transaction_id'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
