"""feat: Add epoch and watermark model for reprocessing

Revision ID: d9e2b3a0c1f4
Revises: 41f42bda6d1e
Create Date: 2025-08-25 21:40:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9e2b3a0c1f4'
down_revision: Union[str, None] = '41f42bda6d1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Create the new position_state table
    op.create_table('position_state',
    sa.Column('portfolio_id', sa.String(), nullable=False),
    sa.Column('security_id', sa.String(), nullable=False),
    sa.Column('epoch', sa.Integer(), server_default='0', nullable=False),
    sa.Column('watermark_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), server_default='CURRENT', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('portfolio_id', 'security_id')
    )
    op.create_index(op.f('ix_position_state_status'), 'position_state', ['status'], unique=False)

    # 2. Add 'epoch' column to versioned tables with a server default
    op.add_column('daily_position_snapshots', sa.Column('epoch', sa.Integer(), server_default='0', nullable=False))
    op.add_column('portfolio_timeseries', sa.Column('epoch', sa.Integer(), server_default='0', nullable=False))
    op.add_column('portfolio_valuation_jobs', sa.Column('epoch', sa.Integer(), server_default='0', nullable=False))
    op.add_column('position_history', sa.Column('epoch', sa.Integer(), server_default='0', nullable=False))
    op.add_column('position_timeseries', sa.Column('epoch', sa.Integer(), server_default='0', nullable=False))

    # 3. Update constraints and primary keys to include the new epoch column
    op.drop_constraint('_portfolio_security_date_uc', 'daily_position_snapshots', type_='unique')
    op.create_unique_constraint('_portfolio_security_date_epoch_uc', 'daily_position_snapshots', ['portfolio_id', 'security_id', 'date', 'epoch'])

    op.drop_constraint('portfolio_timeseries_pkey', 'portfolio_timeseries', type_='primary')
    op.create_primary_key('portfolio_timeseries_pkey', 'portfolio_timeseries', ['portfolio_id', 'date', 'epoch'])

    op.drop_constraint('_portfolio_security_valuation_date_uc', 'portfolio_valuation_jobs', type_='unique')
    op.create_unique_constraint('_portfolio_security_valuation_date_epoch_uc', 'portfolio_valuation_jobs', ['portfolio_id', 'security_id', 'valuation_date', 'epoch'])

    op.drop_constraint('position_timeseries_pkey', 'position_timeseries', type_='primary')
    op.create_primary_key('position_timeseries_pkey', 'position_timeseries', ['portfolio_id', 'security_id', 'date', 'epoch'])

    # 4. Drop the old recalculation_jobs table
    op.drop_index(op.f('ix_recalculation_jobs_portfolio_id'), table_name='recalculation_jobs')
    op.drop_index(op.f('ix_recalculation_jobs_security_id'), table_name='recalculation_jobs')
    op.drop_index(op.f('ix_recalculation_jobs_status'), table_name='recalculation_jobs')
    op.drop_table('recalculation_jobs')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Re-create the recalculation_jobs table
    op.create_table('recalculation_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.String(), nullable=False),
    sa.Column('security_id', sa.String(), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recalculation_jobs_status'), 'recalculation_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_recalculation_jobs_security_id'), 'recalculation_jobs', ['security_id'], unique=False)
    op.create_index(op.f('ix_recalculation_jobs_portfolio_id'), 'recalculation_jobs', ['portfolio_id'], unique=False)

    # 2. Revert constraints and primary keys
    op.drop_constraint('position_timeseries_pkey', 'position_timeseries', type_='primary')
    op.create_primary_key('position_timeseries_pkey', 'position_timeseries', ['portfolio_id', 'security_id', 'date'])

    op.drop_constraint('_portfolio_security_valuation_date_epoch_uc', 'portfolio_valuation_jobs', type_='unique')
    op.create_unique_constraint('_portfolio_security_valuation_date_uc', 'portfolio_valuation_jobs', ['portfolio_id', 'security_id', 'valuation_date'])

    op.drop_constraint('portfolio_timeseries_pkey', 'portfolio_timeseries', type_='primary')
    op.create_primary_key('portfolio_timeseries_pkey', 'portfolio_timeseries', ['portfolio_id', 'date'])

    op.drop_constraint('_portfolio_security_date_epoch_uc', 'daily_position_snapshots', type_='unique')
    op.create_unique_constraint('_portfolio_security_date_uc', 'daily_position_snapshots', ['portfolio_id', 'security_id', 'date'])

    # 3. Drop the 'epoch' columns
    op.drop_column('position_timeseries', 'epoch')
    op.drop_column('position_history', 'epoch')
    op.drop_column('portfolio_valuation_jobs', 'epoch')
    op.drop_column('portfolio_timeseries', 'epoch')
    op.drop_column('daily_position_snapshots', 'epoch')

    # 4. Drop the new position_state table
    op.drop_index(op.f('ix_position_state_status'), table_name='position_state')
    op.drop_table('position_state')

    # ### end Alembic commands ###