"""refactor(db): Remove unique constraint from PositionHistory transaction_id

Revision ID: db3a439c9337
Revises: 19b67c2d3897
Create Date: 2025-07-30 09:37:09.711945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db3a439c9337'
down_revision: Union[str, None] = '19b67c2d3897'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('position_history_transaction_id_key', 'position_history', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('position_history_transaction_id_key', 'position_history', ['transaction_id'])
    # ### end Alembic commands ###
