"""feat: add lifecycle columns to valuation_jobs

Revision ID: ded0859f2881
Revises: d9e2b3a0c1f4
Create Date: 2025-08-26 23:15:35.760062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '<your_new_revision_id>'
down_revision: Union[str, None] = 'd9e2b3a0c1f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_valuation_jobs', sa.Column('failure_reason', sa.Text(), nullable=True))
    op.add_column('portfolio_valuation_jobs', sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio_valuation_jobs', 'attempt_count')
    op.drop_column('portfolio_valuation_jobs', 'failure_reason')
    # ### end Alembic commands ###