"""refactor: Remove daily_performance_metrics table

Revision ID: 2b1a3c4d5e6f
Revises: 13f0d8f9e1df
Create Date: 2025-08-18 12:45:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b1a3c4d5e6f' # NOTE: Replace with your actual revision ID if different
down_revision: Union[str, None] = '13f0d8f9e1df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_daily_performance_metrics_portfolio_date_basis', table_name='daily_performance_metrics')
    op.drop_index(op.f('ix_daily_performance_metrics_date'), table_name='daily_performance_metrics')
    op.drop_table('daily_performance_metrics')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_performance_metrics',
    sa.Column('portfolio_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('return_basis', sa.String(), nullable=False),
    sa.Column('linking_factor', sa.Numeric(precision=28, scale=18), nullable=False),
    sa.Column('daily_return_pct', sa.Numeric(precision=28, scale=18), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.portfolio_id'], ),
    sa.PrimaryKeyConstraint('portfolio_id', 'date', 'return_basis')
    )
    op.create_index(op.f('ix_daily_performance_metrics_date'), 'daily_performance_metrics', ['date'], unique=False)
    op.create_index('ix_daily_performance_metrics_portfolio_date_basis', 'daily_performance_metrics', ['portfolio_id', 'date', 'return_basis'], unique=False)
    # ### end Alembic commands ###