"""create transaction_costs table and add unique constraint

Revision ID: e3d357b25dfa
Revises: 0188e60bbbba
Create Date: 2025-07-14 15:16:47.669125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3d357b25dfa'
down_revision: Union[str, None] = '0188e60bbbba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'transaction_costs',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('transaction_id', sa.String(), nullable=False),
        sa.Column('portfolio_id', sa.String(), nullable=False),
        sa.Column('instrument_id', sa.String(), nullable=False),
        sa.Column('transaction_date', sa.Date(), nullable=False),
        sa.Column('cost_amount', sa.Float(), nullable=False),
        sa.Column('cost_currency', sa.String(), nullable=False),
        sa.Column('calculation_date', sa.DateTime(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False), # Note: kept as nullable=False based on model definition
        sa.PrimaryKeyConstraint('id', name=op.f('pk_transaction_costs')),
        sa.UniqueConstraint('transaction_id', 'portfolio_id', 'instrument_id', 'transaction_date', name='uq_transaction_cost_business_key')
    )
    op.create_index(op.f('ix_transaction_costs_instrument_id'), 'transaction_costs', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_transaction_costs_portfolio_id'), 'transaction_costs', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_transaction_costs_transaction_date'), 'transaction_costs', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_transaction_costs_transaction_id'), 'transaction_costs', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_costs_transaction_id'), table_name='transaction_costs')
    op.drop_index(op.f('ix_transaction_costs_transaction_date'), table_name='transaction_costs')
    op.drop_index(op.f('ix_transaction_costs_portfolio_id'), table_name='transaction_costs')
    op.drop_index(op.f('ix_transaction_costs_instrument_id'), table_name='transaction_costs')
    op.drop_table('transaction_costs')
    # ### end Alembic commands ###