"""fix: Add composite unique constraint to processed_events

Revision ID: e914a5a5874e
Revises: c824b2f1a6e9
Create Date: 2025-08-02 14:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e914a5a5874e'
down_revision: Union[str, None] = 'c824b2f1a6e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('processed_events_event_id_key', 'processed_events', type_='unique')
    op.create_unique_constraint('_event_service_uc', 'processed_events', ['event_id', 'service_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_event_service_uc', 'processed_events', type_='unique')
    op.create_unique_constraint('processed_events_event_id_key', 'processed_events', ['event_id'])
    # ### end Alembic commands ###