"""perf: add covering index for latest position query

Revision ID: e91fbfa909c4
Revises: eff09d34d409
Create Date: 2025-08-11 23:48:05.793942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e91fbfa909c4'
down_revision: Union[str, None] = 'eff09d34d409'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_daily_position_snapshots_covering', 'daily_position_snapshots', ['portfolio_id', 'security_id', sa.text('date DESC'), sa.text('id DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_daily_position_snapshots_covering', table_name='daily_position_snapshots')
    # ### end Alembic commands ###
