"""feat: add portfolio_valuation_jobs table

Revision ID: eff09d34d409
Revises: 8fc322b428d0
Create Date: 2025-08-11 19:41:50.542500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eff09d34d409'
down_revision: Union[str, None] = '8fc322b428d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_valuation_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.String(), nullable=False),
    sa.Column('security_id', sa.String(), nullable=False),
    sa.Column('valuation_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'security_id', 'valuation_date', name='_portfolio_security_valuation_date_uc')
    )
    op.create_index(op.f('ix_portfolio_valuation_jobs_portfolio_id'), 'portfolio_valuation_jobs', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_portfolio_valuation_jobs_security_id'), 'portfolio_valuation_jobs', ['security_id'], unique=False)
    op.create_index(op.f('ix_portfolio_valuation_jobs_status'), 'portfolio_valuation_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_portfolio_valuation_jobs_valuation_date'), 'portfolio_valuation_jobs', ['valuation_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_valuation_jobs_valuation_date'), table_name='portfolio_valuation_jobs')
    op.drop_index(op.f('ix_portfolio_valuation_jobs_status'), table_name='portfolio_valuation_jobs')
    op.drop_index(op.f('ix_portfolio_valuation_jobs_security_id'), table_name='portfolio_valuation_jobs')
    op.drop_index(op.f('ix_portfolio_valuation_jobs_portfolio_id'), table_name='portfolio_valuation_jobs')
    op.drop_table('portfolio_valuation_jobs')
    # ### end Alembic commands ###
