"""refactor(db): add transaction to cashflow relationship

Revision ID: fac2be404322
Revises: 5acfa4e4da10
Create Date: 2025-07-28 21:25:24.909341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fac2be404322'
down_revision: Union[str, None] = '5acfa4e4da10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
