[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cost-calculator-service"
version = "0.1.0"
description = "Portfolio Analytics - Cost Calculator Service"
requires-python = ">=3.11"

[tool.setuptools.packages.find]
where = ["app"]