from enum import StrEnum


class BuyValidationReasonCode(StrEnum):
    INVALID_TRANSACTION_TYPE = "BUY_001_INVALID_TRANSACTION_TYPE"
    MISSING_SETTLEMENT_DATE = "BUY_002_MISSING_SETTLEMENT_DATE"
    NON_POSITIVE_QUANTITY = "BUY_003_NON_POSITIVE_QUANTITY"
    NON_POSITIVE_GROSS_AMOUNT = "BUY_004_NON_POSITIVE_GROSS_AMOUNT"
    MISSING_TRADE_CURRENCY = "BUY_005_MISSING_TRADE_CURRENCY"
    MISSING_BOOK_CURRENCY = "BUY_006_MISSING_BOOK_CURRENCY"
    INVALID_DATE_ORDER = "BUY_007_INVALID_DATE_ORDER"
    MISSING_LINKAGE_IDENTIFIER = "BUY_008_MISSING_LINKAGE_IDENTIFIER"
    MISSING_POLICY_METADATA = "BUY_009_MISSING_POLICY_METADATA"

