from enum import StrEnum


class SellValidationReasonCode(StrEnum):
    INVALID_TRANSACTION_TYPE = "SELL_001_INVALID_TRANSACTION_TYPE"
    MISSING_SETTLEMENT_DATE = "SELL_002_MISSING_SETTLEMENT_DATE"
    NON_POSITIVE_QUANTITY = "SELL_003_NON_POSITIVE_QUANTITY"
    NON_POSITIVE_GROSS_AMOUNT = "SELL_004_NON_POSITIVE_GROSS_AMOUNT"
    MISSING_TRADE_CURRENCY = "SELL_005_MISSING_TRADE_CURRENCY"
    MISSING_BOOK_CURRENCY = "SELL_006_MISSING_BOOK_CURRENCY"
    INVALID_DATE_ORDER = "SELL_007_INVALID_DATE_ORDER"
    MISSING_LINKAGE_IDENTIFIER = "SELL_008_MISSING_LINKAGE_IDENTIFIER"
    MISSING_POLICY_METADATA = "SELL_009_MISSING_POLICY_METADATA"
